In [3]:
import numpy as np

In [4]:


from pandas import Series, DataFrame
import pandas as pd


In [5]:
obj=Series([4,7,-5,3])

In [6]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [7]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [8]:
obj2=Series([4,7,-5,3],index=['d','b','a','c'])

In [9]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [10]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [11]:
obj2['a']

-5

In [12]:
obj2[obj2>0]

d    4
b    7
c    3
dtype: int64

In [13]:
obj2*2

d     8
b    14
a   -10
c     6
dtype: int64

In [14]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [15]:
'b'in obj2

True

In [16]:
sdata={'Ohio':35000,'Texas':71000,'Oregon':16000,'Utah':5000}

In [17]:
obj3=Series(sdata)

In [18]:
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [19]:
state=['Califonia','Ohio','Oregon','Texas']

In [20]:
obj4=Series(sdata,index=state)

In [21]:
obj4

Califonia        NaN
Ohio         35000.0
Oregon       16000.0
Texas        71000.0
dtype: float64

In [22]:
pd.isnull(obj4)

Califonia     True
Ohio         False
Oregon       False
Texas        False
dtype: bool

In [23]:
pd.notnull(obj4)

Califonia    False
Ohio          True
Oregon        True
Texas         True
dtype: bool

In [24]:
obj4.isnull()

Califonia     True
Ohio         False
Oregon       False
Texas        False
dtype: bool

In [25]:
obj3+obj4

Califonia         NaN
Ohio          70000.0
Oregon        32000.0
Texas        142000.0
Utah              NaN
dtype: float64

In [26]:
data={'state':['Ohio','Ohio','Ohio','Nevada','Nevada'],'year':[2000,2001,2002,2001,2002],'pop':[1.5,1.7,3.6,2.4,2.9]}

In [27]:
frame=DataFrame(data)

In [28]:
frame


pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [29]:
DataFrame(data,columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [30]:
frame2=DataFrame(data,columns=['year','state','pop','debt'],index=['one','two','three','four','five'])

In [31]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [32]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [33]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [34]:
frame2['debt']=16.5

In [35]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [36]:
frame2['debt']=np.arange(5.)

In [37]:
frame2


year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0

In [38]:

frame2['eastern']=frame2.state=='Ohio'

In [39]:
frame2


year   state  pop  debt  eastern
one    2000    Ohio  1.5   0.0     True
two    2001    Ohio  1.7   1.0     True
three  2002    Ohio  3.6   2.0     True
four   2001  Nevada  2.4   3.0    False
five   2002  Nevada  2.9   4.0    False

In [40]:
pop={'Nevada':{2001:2.4,2002:2.9},'Ohio':{2000:1.5,2001:1.7,2002:3.6}}

In [41]:
frame3=DataFrame(pop)

In [42]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [43]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [44]:
frame3.index.name='year'

In [45]:
frame3.columns.name='state'

In [46]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [47]:
frame3.values

array([[ nan,  1.5],
       [ 2.4,  1.7],
       [ 2.9,  3.6]])

In [48]:
'Ohio'in frame3.columns

True

In [49]:
2002 in frame3.index

True

In [50]:
obj.reindex(['a','b','c','d','e'])

a   NaN
b   NaN
c   NaN
d   NaN
e   NaN
dtype: float64

In [51]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [52]:
obj2=Series([3,2,4,5,6],index=['a','b','c','d','e'])

In [53]:
obj2

a    3
b    2
c    4
d    5
e    6
dtype: int64

In [54]:
obj2.reindex(['a','b','c','d','e','f'])

a    3.0
b    2.0
c    4.0
d    5.0
e    6.0
f    NaN
dtype: float64

In [55]:
obj2.reindex(['a','b','c','d','e','f'],fill_value=0)

a    3
b    2
c    4
d    5
e    6
f    0
dtype: int64

In [56]:
obj3=Series(['blue','red','yellow'],index=[0,2,4])

In [57]:
obj3.reindex(range(6),method='ffill')

0      blue
1      blue
2       red
3       red
4    yellow
5    yellow
dtype: object

### dropping entries from an axis

In [58]:
obj=Series(np.arange(5.),index=['a','b','c','d','e'])

In [59]:
new_obj=obj.drop('c')

In [60]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [61]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [62]:
frame3.drop('Ohio',axis=1)

state  Nevada
year         
2000      NaN
2001      2.4
2002      2.9

### Indexing, Selection, and filtering


In [63]:
obj['b']

1.0

In [64]:
obj[1]

1.0

In [65]:
obj[0]

0.0

In [66]:
obj['a']

0.0

In [67]:
obj[['b','c']]

b    1.0
c    2.0
dtype: float64

In [68]:
frame[:2]

pop state  year
0  1.5  Ohio  2000
1  1.7  Ohio  2001

### Arithmetic and data alignment


In [69]:
s1=Series([7.3,-2.5,3.4,1.5],index=['a','c','d','e'])

In [70]:
s2=Series([-2.1,3.6,-1.5,4,3.1],index=['a','c','e','f','g'])

In [71]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [72]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [73]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [74]:
 df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),index=['Ohio', 'Texas', 'Colorado'])

In [75]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [76]:
df2=DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [77]:
np.arange(16.).reshape((4,4))

array([[  0.,   1.,   2.,   3.],
       [  4.,   5.,   6.,   7.],
       [  8.,   9.,  10.,  11.],
       [ 12.,  13.,  14.,  15.]])

In [78]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [79]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [80]:
df1+df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

### Arithmetic methods with fill values

In [81]:
df1=DataFrame(np.arange(12.).reshape((3,4)),columns=list('abcd'))

In [82]:
df2=DataFrame(np.arange(20.).reshape((4,5)),columns=list('abcde'))

In [83]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [84]:
df1.add(df2,fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [85]:
df1.reindex(columns=df2.columns,fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

### Operations between DataFrame and Series


In [86]:
arr=np.arange(12.).reshape((3,4))

In [87]:
arr

array([[  0.,   1.,   2.,   3.],
       [  4.,   5.,   6.,   7.],
       [  8.,   9.,  10.,  11.]])

In [88]:
arr[0]

array([ 0.,  1.,  2.,  3.])

In [89]:
arr-arr[0]

array([[ 0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.],
       [ 8.,  8.,  8.,  8.]])

In [90]:
frame=DataFrame(np.arange(12.).reshape((4,3)),columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])

In [91]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [92]:
series=frame.iloc[0]

In [93]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [94]:
frame-series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [95]:
series2=Series(range(3),index=list('bef'))

In [96]:
series2

b    0
e    1
f    2
dtype: int32

In [97]:
frame+series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [98]:
series3=frame['d']

In [99]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [100]:
frame.sub(series3,axis=0)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

### Function application and mapping


In [101]:
frame=DataFrame(np.random.randn(4,3),columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])

In [102]:
frame

b         d         e
Utah    0.223269  0.895352 -0.365493
Ohio   -0.037374 -1.130009 -1.482091
Texas  -1.497680  0.497798  0.413510
Oregon  0.602588  1.161128  0.319052

In [103]:
f=lambda x : x.max()-x.min()

In [104]:
frame.apply(f)

b    2.100268
d    2.291138
e    1.895601
dtype: float64

In [105]:
frame.apply(f,axis=1)

Utah      1.260845
Ohio      1.444717
Texas     1.995478
Oregon    0.842076
dtype: float64

In [106]:
def f(x):
    return Series([x.min(),x.max()],index=['min','max'])

In [107]:
frame.apply(f)

b         d         e
min -1.497680 -1.130009 -1.482091
max  0.602588  1.161128  0.413510

In [108]:
format=lambda x:'%.2f'%x

In [109]:
frame.applymap(format)

b      d      e
Utah     0.22   0.90  -0.37
Ohio    -0.04  -1.13  -1.48
Texas   -1.50   0.50   0.41
Oregon   0.60   1.16   0.32

In [110]:
frame['e'].map(format)

Utah      -0.37
Ohio      -1.48
Texas      0.41
Oregon     0.32
Name: e, dtype: object

### Sorting and ranking

In [111]:
obj=Series(range(4),index=['d','a','b','c'])

In [112]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int32

In [113]:
frame=DataFrame(np.arange(8).reshape((2,4)),index=['three','one'],columns=['d','a','b','c'])

In [114]:
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [115]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [116]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [117]:
frame.sort_index(axis=1,ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [118]:
obj=Series([4,7,-3,2])

In [119]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [120]:
obj=Series([4,np.nan,7,np.nan,-3,2])

In [121]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [122]:
frame=DataFrame({'b':[4,7,-3,2],'a':[0,1,0,1]})

In [123]:
frame

a  b
0  0  4
1  1  7
2  0 -3
3  1  2

In [124]:
frame.sort_values(by='b')

a  b
2  0 -3
3  1  2
0  0  4
1  1  7

In [125]:
frame.sort_values(by=['a','b'])

a  b
2  0 -3
0  0  4
3  1  2
1  1  7

In [126]:
obj=Series([7,-5,7,4,2,0,4])

In [127]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [128]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [129]:
obj.rank(ascending=False,method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [130]:
frame=DataFrame({'b':[4.3,7,-3,2],'a':[0,1,0,1],'c':[-2,5,8,-2.5]})

In [131]:
frame

a    b    c
0  0  4.3 -2.0
1  1  7.0  5.0
2  0 -3.0  8.0
3  1  2.0 -2.5

In [132]:
frame.rank(axis=1)

a    b    c
0  2.0  3.0  1.0
1  1.0  3.0  2.0
2  2.0  1.0  3.0
3  2.0  3.0  1.0

### summarizing and computing descriptive statistics

In [133]:
df=DataFrame([[1.4,np.nan],[7.1,-4.5],[np.nan,np.nan],[0.75,-1.3]],index=['a','b','c','d'],columns=['one','two'])

In [134]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [135]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [136]:
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [137]:
df.mean(axis=1,skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [138]:
df.idxmax()

one    b
two    d
dtype: object

In [139]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [140]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [141]:
obj=Series(['a','a','b','c']*4)

In [142]:
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [143]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

## Yahoo Finance
### Correlation and Covariance



In [148]:
import pip
pip.main(['install','pandas_datareader'])
pip.main(['install','git+https://github.com/pydata/pandas-datareader.git'])

from pandas_datareader import data, wb
import pandas as pd
import pandas_datareader.data as web

all_data = {ticker: web.get_data_yahoo(ticker)
            for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

price = pd.DataFrame({ticker: data['Adj Close']
                     for ticker, data in all_data.items()})
volume = pd.DataFrame({ticker: data['Volume']
                      for ticker, data in all_data.items()})

  Cloning https://github.com/pydata/pandas-datareader.git to c:\users\yuezh\appdata\local\temp\pip-l67s8voj-build


In [150]:
returns=price.pct_change()
price.head()

AAPL        GOOG         IBM       MSFT
Date                                                    
2010-01-04  27.406532  311.349976  108.093323  25.148876
2010-01-05  27.453915  309.978882  106.787575  25.157001
2010-01-06  27.017223  302.164703  106.093880  25.002611
2010-01-07  26.967278  295.130463  105.726646  24.742592
2010-01-08  27.146566  299.064880  106.787575  24.913233

In [152]:
price.head()

AAPL        GOOG         IBM       MSFT
Date                                                    
2010-01-04  27.406532  311.349976  108.093323  25.148876
2010-01-05  27.453915  309.978882  106.787575  25.157001
2010-01-06  27.017223  302.164703  106.093880  25.002611
2010-01-07  26.967278  295.130463  105.726646  24.742592
2010-01-08  27.146566  299.064880  106.787575  24.913233

In [153]:
returns.head()

AAPL      GOOG       IBM      MSFT
Date                                              
2010-01-04       NaN       NaN       NaN       NaN
2010-01-05  0.001729 -0.004404 -0.012080  0.000323
2010-01-06 -0.015906 -0.025209 -0.006496 -0.006137
2010-01-07 -0.001849 -0.023279 -0.003461 -0.010400
2010-01-08  0.006648  0.013331  0.010035  0.006897

In [154]:
returns['MSFT'].corr(returns['IBM'])

0.46741107888985484

In [155]:
returns['MSFT'].cov(returns['IBM'])

7.7664750723029091e-05

In [156]:
returns.corr()

AAPL      GOOG       IBM      MSFT
AAPL  1.000000  0.415742  0.356212  0.396261
GOOG  0.415742  1.000000  0.380283  0.480013
IBM   0.356212  0.380283  1.000000  0.467411
MSFT  0.396261  0.480013  0.467411  1.000000

In [157]:
returns.cov()

AAPL      GOOG       IBM      MSFT
AAPL  0.000255  0.000101  0.000067  0.000089
GOOG  0.000101  0.000230  0.000068  0.000102
IBM   0.000067  0.000068  0.000140  0.000078
MSFT  0.000089  0.000102  0.000078  0.000198

In [158]:
returns.corrwith(returns.IBM)

AAPL    0.356212
GOOG    0.380283
IBM     1.000000
MSFT    0.467411
dtype: float64

In [159]:
returns.corrwith(volume)

AAPL   -0.069951
GOOG   -0.013785
IBM    -0.158135
MSFT   -0.087653
dtype: float64

### Unique Values, Value Counts, and Membership

In [160]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [161]:
uniques = obj.unique()

In [162]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [163]:
pd.value_counts(obj.values, sort=False)

d    1
b    2
a    3
c    3
dtype: int64

In [164]:
 obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [165]:
mask = obj.isin(['b', 'c'])

In [166]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [167]:
 obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [168]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])

In [169]:
unique_vals = pd.Series(['c', 'b', 'a'])

In [170]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [171]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
                      'Qu2': [2, 3, 1, 2, 3],
                     'Qu3': [1, 5, 2, 4, 4]})

In [172]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [173]:
data.describe()

Qu1      Qu2       Qu3
count  5.000000  5.00000  5.000000
mean   3.000000  2.20000  3.200000
std    1.224745  0.83666  1.643168
min    1.000000  1.00000  1.000000
25%    3.000000  2.00000  2.000000
50%    3.000000  2.00000  4.000000
75%    4.000000  3.00000  4.000000
max    4.000000  3.00000  5.000000

In [174]:
result = data.apply(pd.value_counts).fillna(0)

In [175]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0


## 